# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0003_useremail_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='newsletter',
        ),
    ]
