# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0004_auto_20151230_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='pub_date',
        ),
    ]
